import './globals.css';
//import { Inter } from 'next/font/google';
import Providers from './Provider';
//import Navbar from './componant/Navbar';
//import Test from './componant/Test';
//const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="m-2 p-2 text-justify text-gray-800 dark:bg-gray-900 dark:text-gray-200">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}